# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui_designer/newpro.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NewPro(object):
    def setupUi(self, NewPro):
        NewPro.setObjectName("NewPro")
        NewPro.resize(452, 177)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        NewPro.setFont(font)
        self.label = QtWidgets.QLabel(NewPro)
        self.label.setGeometry(QtCore.QRect(20, 20, 71, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(NewPro)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 71, 21))
        self.label_2.setObjectName("label_2")
        self.SoftwareName = QtWidgets.QLineEdit(NewPro)
        self.SoftwareName.setGeometry(QtCore.QRect(90, 20, 331, 20))
        self.SoftwareName.setObjectName("SoftwareName")
        self.SoftwareVersion = QtWidgets.QLineEdit(NewPro)
        self.SoftwareVersion.setGeometry(QtCore.QRect(90, 60, 331, 20))
        self.SoftwareVersion.setObjectName("SoftwareVersion")
        self.pushButton = QtWidgets.QPushButton(NewPro)
        self.pushButton.setGeometry(QtCore.QRect(300, 140, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(NewPro)
        self.pushButton_2.setGeometry(QtCore.QRect(120, 140, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(NewPro)
        self.label_3.setGeometry(QtCore.QRect(20, 100, 71, 21))
        self.label_3.setObjectName("label_3")
        self.ProjectPath = QtWidgets.QLineEdit(NewPro)
        self.ProjectPath.setGeometry(QtCore.QRect(90, 100, 301, 20))
        self.ProjectPath.setObjectName("ProjectPath")
        self.ChoosePath = QtWidgets.QToolButton(NewPro)
        self.ChoosePath.setGeometry(QtCore.QRect(400, 100, 21, 21))
        self.ChoosePath.setObjectName("ChoosePath")

        self.retranslateUi(NewPro)
        QtCore.QMetaObject.connectSlotsByName(NewPro)

    def retranslateUi(self, NewPro):
        _translate = QtCore.QCoreApplication.translate
        NewPro.setWindowTitle(_translate("NewPro", "新建工程"))
        self.label.setText(_translate("NewPro", "程 序 名 称："))
        self.label_2.setText(_translate("NewPro", "程序版本号："))
        self.pushButton.setText(_translate("NewPro", "新建"))
        self.pushButton_2.setText(_translate("NewPro", "取消"))
        self.label_3.setText(_translate("NewPro", "工 程 位 置："))
        self.ChoosePath.setText(_translate("NewPro", "..."))
